#!/usr/bin/env node
import * as path from 'path';
import * as fs from 'fs';
import { MemgraphService } from '../../lib/memgraph/service';
import { BUILTIN_RULES } from '../../lib/memgraph/rules';

interface ReportOptions {
  format?: string;
  output?: string;
  includeTimeline?: boolean;
  includeMetrics?: boolean;
}

export async function reportCommand(projectPath: string = '.', options: ReportOptions) {
  const resolvedPath = path.resolve(projectPath);
  const fmt = options.format ?? 'markdown';

  console.log('\n📋  Auto-CHUB Report\n');
  console.log(`📁  Scanning: ${resolvedPath}`);
  console.log(`📄  Format: ${fmt}\n`);

  const customRules = MemgraphService.loadConfigRules(resolvedPath);
  const service = new MemgraphService(customRules);

  const report = await service.analyze(resolvedPath, { withGraph: true });

  let content = '';
  if (fmt === 'json') {
    content = JSON.stringify(report, null, 2);
  } else if (fmt === 'csv') {
    const rows = ['File,Line,Severity,Rule,Snippet,Replacement'];
    for (const f of report.files) {
      for (const finding of f.findings) {
        rows.push([
          finding.filePath, finding.line, finding.severity,
          `"${finding.title}"`, `"${finding.snippet.slice(0, 80)}"`, `"${finding.replacement}"`,
        ].join(','));
      }
    }
    content = rows.join('\n');
  } else {
    // Markdown (default)
    const lines: string[] = [];
    lines.push('# Deprecated API Detection Report');
    lines.push(`\n**Project:** \`${resolvedPath}\``);
    lines.push(`**Generated:** ${new Date().toISOString()}`);
    lines.push(`**Engine:** autochub-context-hub (graphology in-memory graph)\n`);

    lines.push('## Executive Summary\n');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Files Scanned | ${report.scannedFiles} |`);
    lines.push(`| Total Findings | ${report.totalFindings} |`);
    lines.push(`| 🔴 Critical | ${report.criticalCount} |`);
    lines.push(`| 🟠 High | ${report.highCount} |`);
    lines.push(`| 🟡 Medium | ${report.mediumCount} |`);
    lines.push(`| 🔵 Low | ${report.lowCount} |`);
    lines.push(`| Scan Time | ${report.durationMs}ms |`);

    if (options.includeMetrics) {
      lines.push('\n## Risk Overview\n');
      lines.push('| File | Risk Score | Findings |');
      lines.push('|------|-----------|---------|');
      for (const f of report.files) {
        lines.push(`| \`${f.filePath}\` | ${f.riskScore}% | ${f.findings.length} |`);
      }
    }

    lines.push('\n## Findings by File\n');
    for (const file of report.files) {
      lines.push(`### \`${file.filePath}\` — Risk: ${file.riskScore}%\n`);
      for (const f of file.findings) {
        const depth = f.propagationDepth > 0 ? ` _(propagated, depth ${f.propagationDepth})_` : '';
        lines.push(`#### ${f.title}${depth}`);
        lines.push(`- **Severity:** ${f.severity}`);
        lines.push(`- **Line:** ${f.line}`);
        lines.push(`- **Code:** \`${f.snippet.slice(0, 100)}\``);
        lines.push(`- **Fix:** ${f.guidance}`);
        lines.push(`- **Replacement:** \`${f.replacement}\``);
        if (f.docsUrl) lines.push(`- **Docs:** ${f.docsUrl}`);
        lines.push('');
      }
    }

    if (options.includeTimeline) {
      lines.push('## Migration Checklist\n');
      lines.push('Use this checklist to track your migration progress:\n');
      const seen = new Set<string>();
      for (const file of report.files) {
        for (const f of file.findings) {
          if (!seen.has(f.ruleId)) {
            seen.add(f.ruleId);
            lines.push(`- [ ] **${f.title}** → \`${f.replacement}\``);
          }
        }
      }
    }

    lines.push(`\n---\n_Generated by [autochub-context-hub](https://github.com/amanpandadev-dev/autochub-context-hub)_`);
    content = lines.join('\n');
  }

  if (options.output) {
    const outPath = path.resolve(options.output);
    fs.writeFileSync(outPath, content);
    console.log(`✅  Report saved to: ${outPath}\n`);
  } else {
    console.log(content);
  }
}
